name: interi_a_r
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"





dependencies:
  

 
  carousel_slider: ^4.0.0


  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  dot_navigation_bar: ^1.0.1+3
  draggable_scrollbar: ^0.1.0
  equatable: ^2.0.3
  expandable: ^5.0.1
  expandable_bottom_sheet: ^1.1.1+1
  expandable_page_view: ^1.0.6
  extended_image: ^4.1.0
  
  flexible_scrollbar: ^0.1.2
  flutter:
    sdk: flutter
  flutter_animated_button: ^2.0.0
  flutter_iconly: ^1.0.2
  flutter_login: ^3.0.0-beta.1
  flutter_markdown: ^0.6.6
  flutter_swiper_null_safety: ^1.0.2
  font_awesome_flutter: ^9.1.0
  form_field_validator: ^1.1.0
  get: 4.3.8
  getwidget: ^2.0.4
  google_fonts: ^2.1.0
  google_nav_bar: ^5.0.5
  ferry: #[latest-version]
  gql_http_link: #[latest-version]
  line_icons: ^2.0.1
  meta: ">=1.0.0 <2.0.0"
  path_provider: ^2.0.3
  permission_handler: ^8.1.6
  pigeon: ^1.0.2
  progress_state_button: ^1.0.3
  shared_preferences: ^2.0.7
  simple_animations: ^3.1.1
  skeletons: ^0.0.3
  velocity_x: ^3.3.0
  vs_scrollbar: ^0.2.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  ferry_hive_store: ^0.4.4
  animated_bottom_navigation_bar: ^0.3.2
  arkit_plugin: ^1.0.3

dev_dependencies:
  build_runner: #[latest-version]
  flutter_test:
    sdk: flutter
  json_serializable: null
  flutter_lints: 
  ferry_generator:
  

flutter:
  assets:
    - assets/
  uses-material-design: true
