// Autogenerated from Pigeon (v1.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by Api2Host.
NSObject<FlutterMessageCodec> *Api2HostGetCodec(void);

@protocol Api2Host
- (void)initUrls:(nullable NSArray<NSString *> *)urls completion:(void(^)(FlutterError *_Nullable))completion;
@end

extern void Api2HostSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<Api2Host> *_Nullable api);

NS_ASSUME_NONNULL_END
